services:
  app:
    image: flask_todo:latest
    container_name: flask_app
    restart: unless-stopped
    build:
      context: .
    environment:
      # set database credentials
      DB_HOST: mysql
      DB_NAME: dbtodo
      DB_USER: flask
      DB_PASSWORD: 12345

    links:
      # network connection with these services
      - mysql
    depends_on:
      # build those images first
      - mysql
    ports:
      # bind on our 5000 port because most people have 80, 8080 already bound
      - "5001:5000"

  mysql:
    container_name: mysql
    # let's grab from mysql 5.7 image
    image: mysql
    volumes:
        # pass volume named mysql-data to mysql container
      - ./mysql_data:/var/lib/mysql
    restart: unless-stopped
    ports:
      - "3306:3306"
      # credentials
    environment:
      MYSQL_ROOT_PASSWORD: 12345
      MYSQL_DATABASE: dbtodo
      MYSQL_USER: flask
      MYSQL_PASSWORD: 12345

  test:
    image: flask_test:latest
    container_name: flask_test
    restart: unless-stopped
    build:
      context: .
      dockerfile: test.Dockerfile
    links:
      # network connection with these services
      - app 
    depends_on:
      # build those images first
      - app

# volumes definition here
volumes:
  # just a persistance data
  mysql-data:
    driver: local