name: Flask App CI Test

on: [push]

jobs:
  run-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Start Docker Compose
        # הורדנו את המקף בין ה-docker ל-compose
        run: docker compose up -d

      - name: Wait for Server
        run: sleep 10

      - name: Test Endpoint
        run: |
          curl -f http://localhost:5000/ || exit 1

      - name: Cleanup
        # גם כאן הורדנו את המקף
        run: docker compose down
